"use client";
import Footer from "@/components/footer";
import Header from "@/components/header";
import Navigation from "@/components/navigations";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Moc Development Team", url: "https://moc.gov.kh" }],
};

export default function RootLayout({
  children,
  analytics,
  team,
  modal,
}: {
  children: React.ReactNode;
  analytics: React.ReactNode;
  team: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          border: "2px dashed #000",
          padding: "0px 15px 15px 15px",
          margin: 20,
        }}
      >
        <Navigation />
        <h1 style={{ margin: "10px 0px" }}>Root Layout</h1>
        <Header />
        {children}
        {modal}
        <Footer />
      </body>
    </html>
  );
}
